name: CI
on: 
  workflow_dispatch:

jobs:
  build:
    name: Build, Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          branch: main
      
      - name: configure
        run: cmake .
      
      - name: build
        run: make
