name: build
on: 
  workflow_dispatch:

jobs:
  build:
    name: Build, Upload
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10' 
      
      - name: configure
        run: cmake .
      
      - name: build
        run: make

      - name: rename
        run: ls | grep precomp_py*.so | xargs -I orig mv orig precomp_py.so
      - name: upload and release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            libprecomp_dll_shared.so
            libprecomp_dll_static.a
            precomp
            precomp_py.so
          tag_name: v0.1919.810
          body: custom build precomp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
